name: Playwright Tests leo

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
   inputs:
      test-to-run:
        description: 'Add your npx code'
        required: false
        default: 'npm run script:to:run'
        type: string   
    workers:
      description: 'Number of workers to run tests in parallel'
      required: false
      default: 1
      type: choice
      options:
        - '1'
        - '2'
        - '3'
        - '4'
  browsers:
    description: 'Browsers to run tests on'
    required: false
    default: 'chromium'
    type: choice
    options:
      - 'chromium'
      - 'firefox'
      - 'webkit'
      - 'all'        

jobs:
  playwright-tests:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      env:
        TEST_TO_RUN: ${{ github.event.inputs.test-to-run }}
        WORKERS: ${{ github.event.inputs.workers }}
        BROWSERS: ${{ github.event.inputs.browsers }}  
      run: |
           ${{env.TEST_TO_RUN}} --workers=${{env.WORKERS}} --projects=${{env.BROWSERS}} || npm run generate:report
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/node@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    - name: upload playwright report
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
    - name: upload allure report
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: allure-report
        path: allure-report/
        retention-days: 30
    - name: ZAP Scan
      uses: zaproxy/action-full-scan@v0.13.0
      with:
        target: 'https://the-internet.herokuapp.com/'